// These styles apply to every route in the application
import Header from '../components/Header'
import './globals.css'

export const metadata = {
  title: 'La Nacion Challenge Next.js',
  description: 'Generated by Pehuen Assalone',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className='bg-gray-200'>
        <Header />
        {children}
      </body>
    </html>
  )
}